
<<<<<<< HEAD
baseurl: ""
=======
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 黄琦雲的博客
description: > # this means to ignore newlines until "baseurl:"
  Material theme based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
baseurl: "/"
url: "https://knightyun.github.io"
permalink: /:year/:month/:day/:title
repository: knightyun/knightyun.github.io
paginate: 5

# MatJek specific configurations
github_profile: "https://github.com/knightyun"
user: "黄琦雲"
user_email: "2386209384@qq.com"
# contact_url: "https://goo.gl/tVljbV"
# google_tracking_id: "UA-96359860-1"
# google_site_verification: "UA-96359860-1"
# disqus_shortname: "黄琦雲"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
>>>>>>> parent of 46595a1... Merge branch 'master' of https://github.com/AlexBw777/AlexBw777.github.io
